spring:
  application:
    name: spring-boot-com-kafka
    kafka:
      producer:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        group-id: group-id
topic:
  name: topic-spring-boot-com-kafka
auto:
  create:
    topics:
      enable: true
